title: Video
modelClass: Yamobile\VideoGallery\Models\Video
list: $/yamobile/videogallery/models/video/columns.yaml
recordUrl: "yamobile/videogallery/video/update/:id"
noRecordsMessage: "backend::lang.list.no_records"
recordsPerPage: 20
showSetup: true
showCheckboxes: true
toolbar:
  buttons: list_toolbar
  search:
    prompt: "backend::lang.list.search_prompt"
